config/routes.rb
SampleApp::Application.routes.draw do

  resources :partners

  resources :newsletters

  # http://guides.rubyonrails.org/i18n.html
  scope "/:locale" do
  end

  get '/blogs_:content_type' => 'blogs#index', as: 'blogs_content_type'
  resources :users
  resources :sessions,      only: [:new, :create, :destroy]
  resources :blogs
  root 'static_pages#home'
  match '/privacy_and_security', to: 'static_pages#privacy_and_security', via: 'get'
  match '/terms_of_use', to: 'static_pages#terms_of_use', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  #match '/help',    to: 'static_pages#help',    via: 'get'
  #match '/about',   to: 'static_pages#about',   via: 'get'
  #match '/contact', to: 'static_pages#contact', via: 'get'

  get '*unmatched_route', :to => 'static_pages#nil_routes'


  get 'sitemap.xml', to: 'sitemap#index', as: 'sitemap', defaults: { format: 'xml' }

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }
  validates :title, presence: true, length: {minimum: 6}
  validates :content, presence: true, length: {minimum: 20}


  # Avatar attached
  has_attached_file :picture, :styles => {:medium => "180x100>", :thumb => "90x50>", :large => "500x500>", :normal => "250x250>"}, :default_url => "/images/:style/missing.png", :storage => :s3, :bucket => "",
                    :s3_credentials => Proc.new{|a| a.instance.s3_credentials }
  # Amazon s3
  def s3_credentials
    {:bucket => "", :access_key_id => "", :secret_access_key => ""}
  end

  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  validates_attachment_size :picture, :less_than => 3.megabytes
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :check_if_user_access, only: [:create, :update, :destroy, :edit, :new]

  # GET /blogs
  # GET /blogs.json
  def index
    if params[:content_type] == "news"
      if I18n.locale == :ru
        @blogs = Blog.where(content_type: "news", language: "RU").paginate(page: params[:page])
      else
        @blogs = Blog.where(content_type: "news", language: "EN").paginate(page: params[:page])
      end
    elsif params[:content_type] == "saas"
      if I18n.locale == :ru
        @blogs = Blog.where(content_type: "saas", language: "RU").paginate(page: params[:page])
      else
        @blogs = Blog.where(content_type: "saas", language: "EN").paginate(page: params[:page])
      end
    elsif params[:content_type] == "specials"
      if I18n.locale == :ru
        @blogs = Blog.where(content_type: "specials", language: "RU").paginate(page: params[:page])
      else
        @blogs = Blog.where(content_type: "specials", language: "EN").paginate(page: params[:page])
      end
    elsif params[:content_type] == "companies_news"
      if I18n.locale == :ru
        @blogs = Blog.where(content_type: "companies_news", language: "RU").paginate(page: params[:page])
      else
        @blogs = Blog.where(content_type: "companies_news", language: "EN").paginate(page: params[:page])
      end
    elsif params[:content_type] == ""
      if I18n.locale == :ru
        @blogs = Blog.where(language: "RU").paginate(page: params[:page])
      else
        @blogs = Blog.where(language: "EN").paginate(page: params[:page])
      end
    else
      if I18n.locale == :ru
        @blogs = Blog.where(language: "RU").paginate(page: params[:page])
      else
        @blogs = Blog.where(language: "EN").paginate(page: params[:page])
      end
    end
    respond_to do |format|
      format.html
      format.mobile { render mobile: @blogs }
      # format json for android app
      format.json { render json: @blogs }
      format.xml { render xml: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blog }
      else
        format.html { render action: 'new' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end

  def check_if_user_access
    if current_user && current_user.admin?
    else
      redirect_to root_path
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content, :language, :content_type, :picture)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
  <div class="field">
    <%= f.label (t 'blog.title') %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label (t 'blog.content') %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <p align="center"><%= image_tag @blog.picture.url(:thumb) %></p>
    <%= label_tag (t 'picture') %>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label (t 'blog.language') %><br>
    <%= f.select :language, options_for_select([[(t 'language.en'), "EN"], [(t 'language.ru'), "RU"]], selected: :option, :selected => @blog.language) %>
  </div>
    <div class="field">
      <%= f.label (t 'blog.content_type') %><br>
      <%= f.select :content_type, options_for_select([[(t 'blog.news'), "news"], [(t 'blog.teleport_saas_system'), "saas"], [(t 'blog.specials'), "specials"], [(t 'blog.companies_news'), "companies_news"]], selected: :option, :selected => @blog.content_type) %>
    </div>
  <div class="actions">
    <%= f.submit (t 'button.ok'), class: "btn btn-sm btn-primary" %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog, class: "btn btn-sm btn-primary" %> |
<%= link_to 'Back', blogs_path, class: "btn btn-sm btn-primary" %>

app/views/blogs/index.html.erb
<div class="pages page-blog-list" id="page-blog-list">
  <div class="container">
    <!-- Header -->
    <header>
      <h4 class="line-divider" id="blog" name="blog" style="text-align: center"><%= (t 'menu.blog') %></h4>
    </header>
    <!-- End Header -->

    <div class="row-fluid">
      <div class="col-md-8">
        <!-- Article -->
        <%= will_paginate %>
        <% @blogs.each do |blog| %>
        <article>
          <!-- Blog title -->
          <h4 style="border-bottom: 1px solid #bbb; padding: 13.5px 0;" id="blog_<%= blog.title %>" name="blog_<%= blog.title %>">
            <%= blog.title %></h4>
            <div class="row">
              <h4><div class="col-md-8"><small><%= (t 'blog.created_at') %> <%= blog.created_at.strftime("%d/%m/%Y - %H:%M:%S") %></small></div></h4>
              <div class="col-md-4" style="text-align: right">
                <% case blog.content_type %>
                <% when "news" %>
                    <span class="label label-primary"><%= (t 'blog.news') %></span>
                <% when "saas" %>
                    <span class="label label-warning"><%= (t 'blog.teleport_saas_system') %></span>
                <% when "specials" %>
                    <span class="label label-success"><%= (t 'blog.specials') %></span>
                <% when "companies_news" %>
                    <span class="label label-info"><%= (t 'blog.companies_news') %></span>
                <% else %>
                    <span class="label label-default"><%= (t 'blog.all') %></span>
                <% end %>
              </div>
            </div>

        <p style="text-align: justify"><%= blog.content %></p>

          <% if blog.picture_file_name.nil? || blog.picture_file_name.blank? %>
          <% else %>
              <p style="text-align: center"><%= image_tag blog.picture.url(:large) %></p>
          <% end %>
          </br>
        </article>
            <% if current_user.try(:admin?) %>
        <td><%= link_to 'Show', blog, class: "btn btn-sm btn-primary" %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog), class: "btn btn-sm btn-warning" %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %></td>
            <% else %>
            <% end %>
            <% end %>
        <%= will_paginate %>

      </div>
      <div class="col-md-4">
        <!--Latest news-->
        <div class="block">
          <h4 style="border-bottom: 1px solid #bbb; padding: 13.5px 0;"><%= (t 'blog.latest_news') %></h4>
          <nav class="submenu">
            <ul class="list-unstyled">
              <% @blogs.order("created_at desc").first(5).each do |blog| %>
              <li>
                <%= link_to ("#blog_" + blog.title) do %>
                    <h5><%= blog.title %></h5>
                <% end %>
              </li>
              <% end %>
            </ul>
          </nav>
        </div>
        <!-- Tags -->
        <div class="block">
          <h4 style="border-bottom: 1px solid #bbb; padding: 13.5px 0;"><%= (t 'blog.categories') %></h4>
          <nav class="submenu">
            <ul class="list-unstyled">
              <li>
                  <%= link_to (blogs_path + "#blog") do %>
                    <span class="label label-default"><%= (t 'blog.all') %></span>
                  <% end %>
              </li>
              <li>
                <%= link_to (blogs_content_type_path("news")) do %>
                    <span class="label label-primary"><%= (t 'blog.news') %></span>
                <% end %>
              </li>
              <li>
                <%= link_to (blogs_content_type_path("specials")) do %>
                    <span class="label label-success"><%= (t 'blog.specials') %></span>
                <% end %>
              </li>
              <li>
                <%= link_to (blogs_content_type_path("saas")) do %>
                    <span class="label label-warning"><%= (t 'blog.teleport_saas_system') %></span>
                <% end %>
              </li>
              <li>
                <%= link_to (blogs_content_type_path("companies_news")) do %>
                    <span class="label label-info"><%= (t 'blog.companies_news') %></span>
                <% end %>
              </li>
            </ul>
          </nav>
        </div>
        <!-- Tags -->
        <div class="block">
          <h4 style="border-bottom: 1px solid #bbb; padding: 13.5px 0;"><%= (t 'contact.get_social') %></h4>
          <nav class="submenu">
            <ul class="list-unstyled list-inline">
              <li>
                <a href="https://www.facebook.com/teleportds" target="_blank" class="sicon-facebook"><img alt="" src="/assets/facebook-black@2x.png" style="width: 32px; height: 32px;"></a>
              </li>
              <li>
                <a href="https://plus.google.com/u/0/b/109901919652597210169/+Teleport-ds/posts" target="_blank" class="sicon-youtube"><img alt="" src="/assets/google-plus-black@2x.png" style="width: 32px; height: 32px;"></a>
              </li>
              <li>
                <a href="https://twitter.com/TeleportDS" target="_blank" class="sicon-twitter"><img alt="" src="/assets/twitter-black@2x.png" style="width: 32px; height: 32px;"></a>
              </li>
              <li>
                <a href="http://www.linkedin.com/company/teleport" target="_blank" class="sicon-linkedin"><img alt="" src="/assets/linkedin-black@2x.png" style="width: 32px; height: 32px;"></a>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/blogs/index.mobile.erb
<div class="pages page-blog-list" id="page-blog-list">
  <div class="container">
    <!-- Header -->
    <header>
      <h4 class="line-divider" id="blog" name="blog" style="text-align: center"><%= (t 'menu.blog') %></h4>
    </header>
    <!-- End Header -->

    <div class="row-fluid">
      <div class="col-md-12">
        <!-- Article -->
        <%= will_paginate %>
        <% @blogs.each do |blog| %>
        <article>
          <!-- Blog title -->
          <h4 style="border-bottom: 1px solid #bbb; padding: 13.5px 0;" id="blog_<%= blog.title %>" name="blog_<%= blog.title %>">
            <%= blog.title %></h4>
            <div class="row">
              <h4><div class="col-md-8"><small><%= (t 'blog.created_at') %> <%= blog.created_at.strftime("%d/%m/%Y - %H:%M:%S") %></small></div></h4>
              <div class="col-md-4" style="text-align: right">
                <% case blog.content_type %>
                <% when "news" %>
                    <span class="label label-primary"><%= (t 'blog.news') %></span>
                <% when "saas" %>
                    <span class="label label-warning"><%= (t 'blog.teleport_saas_system') %></span>
                <% when "specials" %>
                    <span class="label label-success"><%= (t 'blog.specials') %></span>
                <% when "companies_news" %>
                    <span class="label label-info"><%= (t 'blog.companies_news') %></span>
                <% else %>
                    <span class="label label-default"><%= (t 'blog.all') %></span>
                <% end %>
              </div>
            </div>

        <p style="text-align: justify"><%= blog.content %></p>
        </article>
            <% end %>
        <%= will_paginate %>

      </div>
    </div>
  </div>
</div>

app/views/blogs/new.html.erb
<h3 style="text-align: center"><%= t ('blog.new_blog')%></h3>

<%= render 'form' %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-md-12">
<p>
  <strong><%= (t 'blog.title') %>:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong><%= (t 'blog.content') %>:</strong>
  <%= @blog.content %>
</p>

<p>
  <strong><%= (t 'blog.language') %>:</strong>
  <%= @blog.language %>
</p>

<p>
  <strong><%= (t 'blog.content_type') %>:</strong>
  <%= @blog.content_type %>
</p>
<p>
    <strong><%= (t 'picture') %>:</strong>
    <%= @blog.picture.url(:thumb) %>
</p>

<%= link_to (t 'button.edit'), edit_blog_path(@blog), class: "btn btn-sm btn-warning" %> |
<%= link_to (t 'button.back'), blogs_path, class: "btn btn-sm btn-primary" %>

</div>
</div>
</div>

app/views/blogs/show.mobile.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-md-12">
<p>
  <strong><%= (t 'blog.title') %>:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong><%= (t 'blog.content') %>:</strong>
  <%= @blog.content %>
</p>

<p>
  <strong><%= (t 'blog.language') %>:</strong>
  <%= @blog.language %>
</p>

<p>
  <strong><%= (t 'blog.content_type') %>:</strong>
  <%= @blog.content_type %>
</p>
<p>
    <strong><%= (t 'picture') %>:</strong>
    <%= @blog.picture.url(:thumb) %>
</p>

<%= link_to (t 'button.edit'), edit_blog_path(@blog), class: "btn btn-sm btn-warning" %> |
<%= link_to (t 'button.back'), blogs_path, class: "btn btn-sm btn-primary" %>

</div>
</div>
</div>