config/routes.rb
SampleApp::Application.routes.draw do

  resources :partners

  resources :newsletters

  # http://guides.rubyonrails.org/i18n.html
  scope "/:locale" do
  end

  get '/blogs_:content_type' => 'blogs#index', as: 'blogs_content_type'
  resources :users
  resources :sessions,      only: [:new, :create, :destroy]
  resources :blogs
  root 'static_pages#home'
  match '/privacy_and_security', to: 'static_pages#privacy_and_security', via: 'get'
  match '/terms_of_use', to: 'static_pages#terms_of_use', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  #match '/help',    to: 'static_pages#help',    via: 'get'
  #match '/about',   to: 'static_pages#about',   via: 'get'
  #match '/contact', to: 'static_pages#contact', via: 'get'

  get '*unmatched_route', :to => 'static_pages#nil_routes'


  get 'sitemap.xml', to: 'sitemap#index', as: 'sitemap', defaults: { format: 'xml' }

end

app/models/partner.rb
class Partner < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }
  validates :name, presence: true
  validates :role, presence: true
  validates :country, presence: true
  VALID_DOMAIN_REGEX = /[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?/ix
  validates :site, presence: true, format: { with: VALID_DOMAIN_REGEX }, length: {maximum: 30}


  # Avatar attached
  #has_attached_file :image, :styles => {:medium => "180x100#", :thumb => "90x50#", :large => "500x500>", :small => "50x50>", :large_m => "500x500#>", :thumb_m => "90x50>", :small_m => "90x90#"}, :default_url => "/images/:style/missing.png", :storage => :s3, :bucket => "teleport_site",
  #                  :s3_credentials => Proc.new{|a| a.instance.s3_credentials }

  has_attached_file :image, :styles => {
      :medium => {:geometry => "180x100#", :processors => [:cropper, :thumbnail]},
      :thumb => {:geometry => "90x50#", :processors => [:cropper, :thumbnail]},
      :large => {:geometry => "500x500>"},
      :small => {:geometry => "50x50>", :processors => [:cropper, :thumbnail]},
      :large_m => {:geometry => "500x500#", :processors => [:cropper, :thumbnail]},
      :small_m => {:geometry => "90x90#", :processors => [:cropper, :thumbnail]},
      :thumb_m => {:geometry => "90x50>", :processors => [:cropper, :thumbnail]}
  }, :default_url => "/images/:style/missing.png", :storage => :s3, :bucket => "", :s3_protocol => :https,:s3_credentials => Proc.new{|a| a.instance.s3_credentials }

  # Amazon s3
  def s3_credentials
    {:bucket => "", :access_key_id => "", :secret_access_key => ""}
  end

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates_attachment_size :image, :less_than => 3.megabytes

  #Cropping
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  #attr_accessor :processing
  after_update :reprocess_avatar, :if => :cropping?

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def avatar_geometry(style = :original)
    @geometry ||= {}
    avatar_path = (image.options[:storage] == :s3) ? image.url(style) : image.path(style)
    @geometry[style] ||= Paperclip::Geometry.from_file(avatar_path)
    #@geometry[style] ||= Paperclip::Geometry.from_file(profile_picture_path)
  end

  private

  def reprocess_avatar
    #avatar.reprocess!
    # don't crop if the user isn't updating the photo
    #   ...or if the photo is already being processed
    #return unless (cropping? && !processing)
    #self.processing = true
    #avatar.reprocess!
    #self.processing = false
  end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  before_action :set_partner, only: [:show, :edit, :update, :destroy]
  before_action :check_if_user_access, only: [:create, :update, :destroy, :edit, :new]

  # GET /partners
  # GET /partners.json
  def index
    @partners = Partner.paginate(page: params[:page])
    respond_to do |format|
      format.html
      format.mobile { render mobile: @partners }
      # format json for android app
      format.json { render json: @partners }
      format.xml { render xml: @partners }
    end
  end

  def index_view
        if params[:country]
          @partners = Partner.paginate(page: params[:page])
          @stores = Partner.where(role: "Store", visible: true, country: params[:country]).paginate(page: params[:page])
          @delivery_companies = Partner.where(role: "Delivery company", visible: true, country: params[:country]).paginate(page: params[:page])
          @partners_r = Partner.where(role: "Partner", visible: true, country: params[:country]).paginate(page: params[:page])
          @companies = Partner.where(role: "Company", visible: true, country: params[:country]).paginate(page: params[:page])
        else
          @partners = Partner.paginate(page: params[:page])
          @stores = Partner.where(role: "Store", visible: true).paginate(page: params[:page])
          @delivery_companies = Partner.where(role: "Delivery company", visible: true).paginate(page: params[:page])
          @partners_r = Partner.where(role: "Partner", visible: true).paginate(page: params[:page])
          @companies = Partner.where(role: "Company", visible: true).paginate(page: params[:page])
        end
    if I18n.locale == :ru || I18n.locale == :ua

    else

    end
  end

  # GET /partners/1
  # GET /partners/1.json
  def show
  end

  # GET /partners/new
  def new
    @partner = Partner.new
  end

  # GET /partners/1/edit
  def edit
  end

  # POST /partners
  # POST /partners.json
  def create
    @partner = Partner.new(partner_params)

    respond_to do |format|
      if @partner.save
        format.html { redirect_to @partner, notice: 'Partner was successfully created.' }
        format.json { render action: 'show', status: :created, location: @partner }
      else
        format.html { render action: 'new' }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /partners/1
  # PATCH/PUT /partners/1.json
  def update
    respond_to do |format|
      if @partner.update(partner_params)
        if params[:partner][:image].blank?
          if @partner.crop_y == "0"
          else
            if(!@partner.crop_x.blank? && !@partner.crop_y.blank? &&
                !@partner.crop_w.blank? &&  !@partner.crop_h.blank?)
              @partner.image.reprocess!
            end
          end
        end
        format.html { redirect_to @partner, notice: 'Partner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partners/1
  # DELETE /partners/1.json
  def destroy
    @partner.destroy
    respond_to do |format|
      format.html { redirect_to partners_url }
      format.json { head :no_content }
    end
  end

  def check_if_user_access
    if current_user && current_user.admin?
    else
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_partner
      @partner = Partner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def partner_params
      params.require(:partner).permit(:name, :site, :visible, :role, :country, :image)
    end
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/views/partners/_crop.html.erb
<% content_for(:head) do %>
    <%= stylesheet_link_tag "jquery.Jcrop" %>
    <%= javascript_include_tag "jquery.Jcrop.min" %>

    <script type="text/javascript" charset="utf-8">
        $(function() {
            $('#cropbox').Jcrop({
                onChange: update_crop,
                onSelect: update_crop,
                setSelect: [0, 0, 500, 500],
                aspectRatio: 1
            });
        });

        function update_crop(coords) {
            var rx = 90/coords.w;
            var ry = 90/coords.h;
            $('#preview').css({
                width: Math.round(rx * <%= @partner.avatar_geometry(:large_m).width %>) + 'px',
                height: Math.round(ry * <%= @partner.avatar_geometry(:large_m).height %>) + 'px',
                marginLeft: '-' + Math.round(rx * coords.x) + 'px',
                marginTop: '-' + Math.round(ry * coords.y) + 'px'
            });
            var ratio = <%= @partner.avatar_geometry(:original).width %> / <%= @partner.avatar_geometry(:large_m).width %>;
            $("#crop_x").val(Math.round(coords.x * ratio));
            $("#crop_y").val(Math.round(coords.y * ratio));
            $("#crop_w").val(Math.round(coords.w * ratio));
            $("#crop_h").val(Math.round(coords.h * ratio));
        }
    </script>
<% end %>
<div class="row">
  <div class="col-md-6">
    <%= label_tag (t 'avatar') %>
      <%= image_tag @partner.image.url(:large_m), :id => "cropbox", class: "img-thumbnail" %>
  </div>
  <div class="col-md-6">
    <div align="center"><%= label_tag t ('preview') %></div>
    <div align="center">
    <div class="img-thumbnail">
      <div style="width:90px; height:90px; overflow:hidden;" class="img-circle">
        <%= image_tag @partner.image.url(:large_m), :id => "preview" %>
      </div>
    </div>
    </div>
    <div>
      <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
          <%= f.hidden_field attribute, :id => attribute %>
      <% end %>
      <!--<%= f.submit (t 'button.ok'), class: "btn btn-primary btn-xs" %>-->
    </div>
  </div>
</div>

app/views/partners/_form.html.erb
<%= form_for(@partner) do |f| %>
  <% if @partner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@partner.errors.count, "error") %> prohibited this partner from being saved:</h2>

      <ul>
      <% @partner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="field">
            <p align="center"><%= image_tag @partner.image.url(:small_m), class: "img-circle" %></p>
            <%= label_tag (t 'picture') %>
            <%= f.file_field :image %>
            <h5>
              <small>90x90</small>
              <% if @partner.new_record? %>
              <% else %>
                  <%= link_to_function (t 'crop'), 'crop_open();' %>.
              <% end %>
            </h5>
            <% if @partner.new_record? %>
            <% else %>
                <div id="crop_logo" style="display:none" >
                  <%= render 'crop', :f => f %>
                </div>
                <div style="border-bottom: 1px solid lightgray; padding-bottom: 2px;"></div>
                <script>
                    function crop_open() {
                        if (document.getElementById('crop_logo').style.display == 'none') {
                            document.getElementById("crop_logo").style.display = "inline";
                        }  else {
                            document.getElementById('crop_logo').style.display = 'none';
                        }
                    }
                </script>
            <% end %>
          </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :site %><br>
    <%= f.text_field :site %>
  </div>
          <div class="row">
            <div class="col-md-1">
              <%= f.check_box :visible, checked: true %>
            </div>
            <div class="col-md-11">
              <%= f.label :visible %>
            </div>
          </div>
  <div class="field">
    <%= f.label :role %><br>
    <% if @partner.new_record? %>
        <%= f.select :role, options_for_select([[(t 'role.store'), "Store"], [(t 'role.delivery_company'), "Delivery company"], [(t 'role.partner'), "Partner"], [(t 'partner.companies'), "Company"]], selected: :option) %>
    <% else %>
        <%= f.select :role, options_for_select([[(t 'role.store'), "Store"], [(t 'role.delivery_company'), "Delivery company"], [(t 'role.partner'), "Partner"], [(t 'partner.companies'), "Company"]], selected: :option, :selected => @partner.role) %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.select :country, options_for_select([[(t 'country.ukraine'), "Ukraine"], [(t 'country.belarus'), "Belarus"], [(t 'country.russia'), "Russia"], [(t 'country.usa'), "USA"], [(t 'country.canada'), "Canada"], [(t 'country.newzeland'), "Newzeland"], [(t 'country.australia'), "Australia"], [(t 'country.austria'), "Austria"], [(t 'country.belgium'), "Belgium"], [(t 'country.germany'), "Germany"], [(t 'country.greece'), "Greece"], [(t 'country.ireland'), "Ireland"], [(t 'country.spain'), "Spain"], [(t 'country.italy'), "Italy"], [(t 'country.latvia'), "Latvia"], [(t 'country.luxembourg'), "Luxembourg"], [(t 'country.netherlands'), "Netherlands"], [(t 'country.portugal'), "Portugal"], [(t 'country.slovakia'), "Slovakia"], [(t 'country.slovenia'), "Slovenia"], [(t 'country.finlandia'), "Finlandia"], [(t 'country.france'), "France"], [(t 'country.estonia'), "Estonia"]], selected: :option) %>
  </div>
  <div class="actions">
    <%= f.submit (t 'button.ok'), class: "btn btn-sm btn-primary" %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/partners/edit.html.erb
<h3 style="text-align: center">Editing partner</h3>

<%= render 'form' %>

app/views/partners/index.html.erb
<h3><p class="text-center"><%= (t 'partner.list_partners')%></p></h3>
<div class="container">
  <div class="row">
    <div class="col-md-12">
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Site</th>
      <th>Visible</th>
      <th>Type</th>
      <th>Country</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <%= will_paginate %>
  <tbody>
    <% @partners.each do |partner| %>
      <tr>
        <td>
          <div class="img-thumbnail" style="border-radius: 100%;">
          <%= image_tag partner.image.url(:small_m), class: "img-circle", style: "with:50px; height:50px;" %>
          </div>
        </td>
        <td><%= partner.name %></td>
        <td><%= partner.site %></td>
        <td><%= partner.visible %></td>
        <td><%= partner.role %></td>
        <td><%= partner.country %></td>
        <td><%= link_to (I18n.t 'button.show'), partner, class: "btn btn-sm btn-primary" %></td>
        <td><%= link_to (I18n.t 'button.edit'), edit_partner_path(partner), class: "btn btn-sm btn-warning" %></td>
        <td><%= link_to (I18n.t 'button.delete'), partner, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Partner', new_partner_path, class: "btn btn-sm btn-primary" %>
    </div>
  </div>
</div>
<%= will_paginate %>

app/views/partners/index_view.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% if @stores.blank? %>
      <% else %>
          <h4 class="text-center" style="border-bottom: 1px solid lightgray; padding-bottom: 5px;"><%= (t 'partner.stores') %></h4>
      <% end %>
      <% @stores.in_groups_of(6).each do |group| %>
          <div class="row">
            <% group.each do |store| %>
                <% if store.nil? %>
                <% else %>
                    <div class="col-md-2">
                      <div class="thumbnail" align="center">
                        <div class="img-thumbnail" style="border-radius: 100%;">
                          <%= image_tag store.image.url(:small_m), class: "img-circle" %>
                        </div>
                        <div class="caption" style="border-top: 1px solid lightgray;">
                          <h5 class="text-center"><%= store.name %></h5>

                          <p style="font-size: 12px;" class="text-center"><%= link_to store.site, "http://" + store.site, :target => "_blank" %></p>
                        </div>
                      </div>
                    </div>
                <% end %>
            <% end %>
          </div>
      <% end %>
    </div>
    <div class="col-md-12">
      <% if @companies.blank? %>
      <% else %>
          <h4 class="text-center" style="border-bottom: 1px solid lightgray; padding-bottom: 5px;"><%= (t 'partner.companies') %></h4>
      <% end %>
      <% @companies.in_groups_of(6).each do |group| %>
          <div class="row">
            <% group.each do |company| %>
                <% if company.nil? %>
                <% else %>
                    <div class="col-md-2">
                      <div class="thumbnail" align="center">
                        <div class="img-thumbnail" style="border-radius: 100%;">
                          <%= image_tag company.image.url(:small_m), class: "img-circle" %>
                        </div>
                        <div class="caption" style="border-top: 1px solid lightgray;">
                          <h5 class="text-center"><%= company.name %></h5>

                          <p style="font-size: 12px;" class="text-center"><%= link_to company.site, "http://" + store.site, :target => "_blank" %></p>
                        </div>
                      </div>
                    </div>
                <% end %>
            <% end %>
          </div>
      <% end %>
    </div>
    <div class="col-md-12">
      <% if @delivery_companies.blank? %>
      <% else %>
          <h4 class="text-center" style="border-bottom: 1px solid lightgray; padding-bottom: 5px;"><%= (t 'partner.delivery_companies') %></h4>
      <% end %>
      <% @delivery_companies.in_groups_of(6).each do |group| %>
          <div class="row">
            <% group.each do |delivery_company| %>
                <% if delivery_company.nil? %>
                <% else %>
                    <div class="col-md-2">
                      <div class="thumbnail" align="center">
                        <div class="img-thumbnail" style="border-radius: 100%;">
                        <%= image_tag delivery_company.image.url(:small_m), class: "img-circle" %>
                        </div>
                        <div class="caption" style="border-top: 1px solid lightgray;">
                          <h5 class="text-center"><%= delivery_company.name %></h5>

                          <p style="font-size: 12px;" class="text-center"><%= link_to delivery_company.site, "http://" + delivery_company.site, :target => "_blank" %></p>
                        </div>
                      </div>
                    </div>
                <% end %>
            <% end %>
          </div>
      <% end %>
    </div>
    <div class="col-md-12">
      <% if @partners_r.blank? %>
      <% else %>
          <h4 class="text-center" style="border-bottom: 1px solid lightgray; padding-bottom: 5px;"><%= (t 'partner.web') %></h4>
      <% end %>
      <% @partners_r.in_groups_of(6).each do |group| %>
          <div class="row">
            <% group.each do |partners_r| %>
                <% if partners_r.nil? %>
                <% else %>
                    <div class="col-md-2">
                      <div class="thumbnail" align="center">
                        <div class="img-thumbnail" style="border-radius: 100%;">
                          <%= image_tag partners_r.image.url(:small_m), class: "img-circle" %>
                        </div>
                        <div class="caption" style="border-top: 1px solid lightgray;">
                          <h5 class="text-center"><%= partners_r.name %></h5>

                          <p style="font-size: 12px;" class="text-center"><%= link_to partners_r.site, "http://" + partners_r.site, :target => "_blank" %></p>
                        </div>
                      </div>
                    </div>
                <% end %>
            <% end %>
          </div>
      <% end %>
    </div>


  </div>
</div>
<div class="container">
  <div class="row">
    <div align="center">
      <%= link_to (teleport_partners_path) do %>
          <button type="button" class="btn btn-default"><%= (t 'role.all') %></button>
      <% end %>
      <%= link_to (teleport_partners_country_path("Ukraine")) do %>
          <button type="button" class="btn btn-default"><%= (t 'country.ukraine') %></button>
      <% end %>
      <%= link_to (teleport_partners_country_path("Belarus")) do %>
          <button type="button" class="btn btn-default"><%= (t 'country.belarus') %></button>
      <% end %>
      <%= link_to (teleport_partners_country_path("Russia")) do %>
          <button type="button" class="btn btn-default"><%= (t 'country.russia') %></button>
      <% end %>
      <%= link_to (teleport_partners_country_path("USA")) do %>
          <button type="button" class="btn btn-default"><%= (t 'country.usa') %></button>
      <% end %>
      <%= link_to (teleport_partners_country_path("Canada")) do %>
          <button type="button" class="btn btn-default"><%= (t 'country.canada') %></button>
      <% end %>
      <%= link_to (teleport_partners_country_path("Newzeland")) do %>
          <button type="button" class="btn btn-default"><%= (t 'country.newzeland') %></button>
      <% end %>
      <%= link_to (teleport_partners_country_path("Australia")) do %>
          <button type="button" class="btn btn-default"><%= (t 'country.australia') %></button>
      <% end %>
      <!--
  <%= link_to (teleport_partners_country_path("Austria")) do %>
      <button type="button" class="btn btn-default"><%= (t 'country.austria') %></button>
  <% end %>
  <%= link_to (teleport_partners_country_path("Belgium")) do %>
      <button type="button" class="btn btn-default"><%= (t 'country.belgium') %></button>
  <% end %>
  <%= link_to (teleport_partners_country_path("Germany")) do %>
      <button type="button" class="btn btn-default"><%= (t 'country.germany') %></button>
  <% end %>
  <%= link_to (teleport_partners_country_path("Greece")) do %>
      <button type="button" class="btn btn-default"><%= (t 'country.greece') %></button>
  <% end %>
  <%= link_to (teleport_partners_country_path("Ireland")) do %>
      <button type="button" class="btn btn-default"><%= (t 'country.ireland') %></button>
  <% end %>
  <%= link_to (teleport_partners_country_path("Spain")) do %>
      <button type="button" class="btn btn-default"><%= (t 'country.spain') %></button>
  <% end %>
  <%= link_to (teleport_partners_country_path("Italy")) do %>
      <button type="button" class="btn btn-default"><%= (t 'country.italy') %></button>
  <% end %>
  <%= link_to (teleport_partners_country_path("Latvia")) do %>
      <button type="button" class="btn btn-default"><%= (t 'country.latvia') %></button>
  <% end %>
  <%= link_to (teleport_partners_country_path("Luxembourg")) do %>
      <button type="button" class="btn btn-default"><%= (t 'country.luxembourg') %></button>
  <% end %>
  <%= link_to (teleport_partners_country_path("Netherlands")) do %>
      <button type="button" class="btn btn-default"><%= (t 'country.netherlands') %></button>
  <% end %>
  <%= link_to (teleport_partners_country_path("Portugal")) do %>
      <button type="button" class="btn btn-default"><%= (t 'country.portugal') %></button>
  <% end %>
  <%= link_to (teleport_partners_country_path("Slovakia")) do %>
      <button type="button" class="btn btn-default"><%= (t 'country.slovakia') %></button>
  <% end %>
  <%= link_to (teleport_partners_country_path("Slovenia")) do %>
      <button type="button" class="btn btn-default"><%= (t 'country.slovenia') %></button>
  <% end %>
  <%= link_to (teleport_partners_country_path("Finlandia")) do %>
      <button type="button" class="btn btn-default"><%= (t 'country.finlandia') %></button>
  <% end %>
  <%= link_to (teleport_partners_country_path("France")) do %>
      <button type="button" class="btn btn-default"><%= (t 'country.france') %></button>
  <% end %>
  <%= link_to (teleport_partners_country_path("Estonia")) do %>
      <button type="button" class="btn btn-default"><%= (t 'country.estonia') %></button>
  <% end %>
  -->
    </div>
  </div>
</div>

app/views/partners/new.html.erb
<h3 style="text-align: center"><%= t ('partner.new_partner')%></h3>

<%= render 'form' %>

<%= link_to 'Back', partners_path %>

app/views/partners/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <p align="center"><%= image_tag @partner.image.url(:small_m), class: "img-circle" %></p>
<p>
  <strong>Name:</strong>
  <%= @partner.name %>
</p>

<p>
  <strong>Site:</strong>
  <%= @partner.site %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @partner.visible %>
</p>

<p>
  <strong>Type:</strong>
  <%= @partner.role %>
</p>

<p>
  <strong>Country:</strong>
  <%= @partner.country %>
</p>

      <%= link_to (t 'button.edit'), edit_partner_path(@partner), class: "btn btn-sm btn-warning" %> |
      <%= link_to (t 'button.back'), partners_path, class: "btn btn-sm btn-primary" %>

    </div>
  </div>
</div>

app/views/partners/show.mobile.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <p align="center"><%= image_tag @partner.image.url(:small_m), class: "img-circle" %></p>
<p>
  <strong>Name:</strong>
  <%= @partner.name %>
</p>

<p>
  <strong>Site:</strong>
  <%= @partner.site %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @partner.visible %>
</p>

<p>
  <strong>Type:</strong>
  <%= @partner.role %>
</p>

<p>
  <strong>Country:</strong>
  <%= @partner.country %>
</p>

      <%= link_to (t 'button.edit'), edit_partner_path(@partner), class: "btn btn-sm btn-warning" %> |
      <%= link_to (t 'button.back'), partners_path, class: "btn btn-sm btn-primary" %>

    </div>
  </div>
</div>