config/routes.rb
SampleApp::Application.routes.draw do

  resources :partners

  resources :newsletters

  # http://guides.rubyonrails.org/i18n.html
  scope "/:locale" do
  end

  get '/blogs_:content_type' => 'blogs#index', as: 'blogs_content_type'
  resources :users
  resources :sessions,      only: [:new, :create, :destroy]
  resources :blogs
  root 'static_pages#home'
  match '/privacy_and_security', to: 'static_pages#privacy_and_security', via: 'get'
  match '/terms_of_use', to: 'static_pages#terms_of_use', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  #match '/help',    to: 'static_pages#help',    via: 'get'
  #match '/about',   to: 'static_pages#about',   via: 'get'
  #match '/contact', to: 'static_pages#contact', via: 'get'

  get '*unmatched_route', :to => 'static_pages#nil_routes'


  get 'sitemap.xml', to: 'sitemap#index', as: 'sitemap', defaults: { format: 'xml' }

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  before_action :set_newsletter, only: [:show, :edit, :update, :destroy]
  before_action :check_role, only: [:index, :show, :edit, :destroy, :update, :create, :new]
  before_action :set_content, only: [:index, :show, :edit, :destroy, :update, :create, :new]

  # GET /newsletters
  # GET /newsletters.json
  def index
    @newsletters = Newsletter.paginate(page: params[:page])
  end

  # GET /newsletters/1
  # GET /newsletters/1.json
  def show
  end

  # GET /newsletters/new
  def new
    @newsletter = Newsletter.new
  end

  # GET /newsletters/1/edit
  def edit
  end

  # POST /newsletters
  # POST /newsletters.json
  def create
    @newsletter = Newsletter.new(newsletter_params)
    respond_to do |format|
      if @newsletter.save
        UserMailer.send_newsletters(@newsletter).deliver
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully created.' }
        format.json { render action: 'show', status: :created, location: @newsletter }
      else
        format.html { render action: 'new' }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsletters/1
  # PATCH/PUT /newsletters/1.json
  def update
    respond_to do |format|
      if @newsletter.update(newsletter_params)
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1
  # DELETE /newsletters/1.json
  def destroy
    @newsletter.destroy
    respond_to do |format|
      format.html { redirect_to newsletters_url }
      format.json { head :no_content }
    end
  end


  def check_role
    if current_user && current_user.admin?
    else
      redirect_to root_path
    end
  end

  def set_content
    @blogs = Blog.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsletter
      @newsletter = Newsletter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsletter_params
      params.require(:newsletter).permit(:to, :blog_id, :status, :language, :subject)
    end
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/newsletters/_form.html.erb
<%= form_for(@newsletter) do |f| %>
  <% if @newsletter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>

      <ul>
      <% @newsletter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="field">
            <%= f.label (t 'newsletters.language') %><br>
            <%= f.select :language, options_for_select([["EN", "EN"], ["RU", "RU"]], selected: :option) %>
          </div>
  <div class="field">
    <%= f.label (t 'newsletters.to') %><br>
    <%= f.text_area :to %>
  </div>

          <div class="field">
            <%= f.label (t 'newsletters.subject') %><br>
            <%= f.select :subject, options_for_select([[(t 'newsletters.subject_news'), (t 'newsletters.subject_news')], [(t 'newsletters.subject_specials'), (t 'newsletters.subject_specials')], [(t 'newsletters.subject_saas_news'), (t 'newsletters.subject_saas_news')], [(t 'newsletters.subject_companies_news'), (t 'newsletters.subject_companies_news')]], selected: :option) %>
          </div>
  <div class="field">
    <%= f.label (t 'newsletters.blog') %><br>
    <%= f.select :blog_id, @blogs.map { |blog| [blog.title, blog.id] } %>
  </div>


  <div class="field">
    <%= f.label (t 'newsletters.status') %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit (I18n.t 'button.ok'), class: "btn btn-large btn-primary" %>
  </div>

        </div>
      </div>
    </div>
<% end %>

app/views/newsletters/edit.html.erb
<h3><p class="text-center"><%= (t 'newsletters.edit')%></p></h3>

<%= render 'form' %>

app/views/newsletters/index.html.erb
<h3><p class="text-center"><%= (t 'newsletters.listing_newsletters')%></p></h3>

<div class="container">
  <div class="row">
    <div class="col-md-12">
<table class="table table-bordered">
  <thead>
    <tr>
      <th><%= (t 'newsletters.to')%></th>
      <th><%= (t 'newsletters.language')%></th>
      <th><%= (t 'newsletters.subject')%></th>
      <th><%= (t 'newsletters.blog')%></th>
      <th><%= (t 'newsletters.blog_title')%></th>
      <th><%= (t 'newsletters.blog_content')%></th>
      <th><%= (t 'newsletters.created_at')%></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <%= will_paginate %>
  <tbody>
    <% @newsletters.each do |newsletter| %>
      <tr>
        <td><%= newsletter.to %></td>
        <td><%= newsletter.language %></td>
        <td><%= newsletter.subject %></td>
        <td><%= newsletter.blog_id %></td>
        <td>
          <% if newsletter.blog_id.nil? || newsletter.blog_id == 0 %>
              <%= (t 'not_found') %>
          <% elsif Blog.where(id: newsletter.blog_id).take.nil? %>
              <%= (t 'not_found') %>
          <% else %>
              <%= Blog.where(id: newsletter.blog_id).take.title %>
          <% end %>
        </td>
        <td>
          <% if newsletter.blog_id.nil? || newsletter.blog_id == 0 %>
              <%= (t 'not_found') %>
          <% elsif Blog.where(id: newsletter.blog_id).take.nil? %>
              <%= (t 'not_found') %>
          <% else %>
              <%= Blog.where(id: newsletter.blog_id).take.content %>
          <% end %>
        </td>
        <td><%= newsletter.created_at.strftime("%d/%m/%Y - %H:%M:%S") %></td>
        <td><%= link_to (I18n.t 'button.show'), newsletter, class: "btn btn-sm btn-primary" %></td>
        <td><%= link_to (I18n.t 'button.edit'), edit_newsletter_path(newsletter), class: "btn btn-sm btn-warning" %></td>
        <td><%= link_to (I18n.t 'button.delete'), newsletter, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to (I18n.t 'newsletters.new'), new_newsletter_path, class: "btn btn-sm btn-primary" %>
    </div>
  </div>
</div>
<%= will_paginate %>

app/views/newsletters/new.html.erb
<h3><p class="text-center"><%= (t 'newsletters.new')%></p></h3>

<%= render 'form' %>

app/views/newsletters/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-md-12">

      <p>
        <strong><%= (t 'newsletters.language')%>:</strong>
        <%= @newsletter.language %>
      </p>
<p>
  <strong><%= (t 'newsletters.to')%>:</strong>
  <%= @newsletter.to %>
</p>

      <p>
        <strong><%= (t 'newsletters.subject')%>:</strong>
        <%= @newsletter.subject %>
      </p>

<p>
  <strong><%= (t 'newsletters.blog')%>:</strong>
  <%= @newsletter.blog_id %>
</p>

<p>
  <strong><%= (t 'newsletters.status')%>:</strong>
  <%= @newsletter.status %>
</p>

      <p>
        <strong><%= (t 'newsletters.created_at')%>:</strong>
        <%= @newsletter.created_at.strftime("%d/%m/%Y - %H:%M:%S") %>
      </p>

</div>
</div>
</div>