config/routes.rb
SampleApp::Application.routes.draw do

  resources :partners

  resources :newsletters

  # http://guides.rubyonrails.org/i18n.html
  scope "/:locale" do
  end

  get '/blogs_:content_type' => 'blogs#index', as: 'blogs_content_type'
  resources :users
  resources :sessions,      only: [:new, :create, :destroy]
  resources :blogs
  root 'static_pages#home'
  match '/privacy_and_security', to: 'static_pages#privacy_and_security', via: 'get'
  match '/terms_of_use', to: 'static_pages#terms_of_use', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  #match '/help',    to: 'static_pages#help',    via: 'get'
  #match '/about',   to: 'static_pages#about',   via: 'get'
  #match '/contact', to: 'static_pages#contact', via: 'get'

  get '*unmatched_route', :to => 'static_pages#nil_routes'


  get 'sitemap.xml', to: 'sitemap#index', as: 'sitemap', defaults: { format: 'xml' }

end

app/views/layouts/_admin.html.erb
</br>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><%= (t 'admin.admin_management') %></h3>
        </div>
        <div class="panel-body">
          <%= link_to (t 'admin.users'), users_path, class: "btn btn-sm btn-primary" %> |
          <%= link_to (t 'admin.mails'), newsletters_path, class: "btn btn-sm btn-warning" %> |
          <%= link_to (t 'admin.partners'), partners_path, class: "btn btn-sm btn-success" %> |
          <%= link_to (t 'admin.site_mobile_version_check'), {:mobile => 1}, class: "btn btn-sm btn-info" %> | | | |

          <%= link_to (t 'admin.new_blog'), new_blog_path, class: "btn btn-sm btn-success" %> |
          <%= link_to (t 'partner.new_partner'), new_partner_path, class: "btn btn-sm btn-success" %> |
          <%= link_to (t 'newsletters.new'), new_newsletter_path, class: "btn btn-sm btn-warning" %> | | | |
          <%= link_to (t 'Sign out'), signout_path, method: "delete", class: "btn btn-sm btn-danger" %> |
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.teleport-ds.com/">www.teleport-ds.com</a>
    All Rights Reserved, 2013. Created by <a href="http://www.proalab.com/" target="_blank">Proalab</a>.
  </small>
  <nav>
    <ul>
      <li><%= link_to (I18n.t 'menu.about_us_f'), root_path + "#about_us" %></li>
      <li>|</li>
      <li><%= link_to (I18n.t 'menu.privacy_and_security'), privacy_and_security_path %></li>
      <li>|</li>
      <li><%= link_to (I18n.t 'menu.terms_of_use'), terms_of_use_path %></li>
      <li>|</li>
      <li><%= link_to (I18n.t 'menu.contact_us_f'), root_path + "#contact_us" %></li>
		<!--<li><a href="http://news.railstutorial.org/">News</a></li> -->
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to image_tag("teleport_logo_eng_0.png", alt: "Teleport SaaS"), root_path + "#top", :class => "brand" %>
      <nav>
        <ul class="nav nav-pills pull-right">
          <!--<li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= (I18n.t 'menu.about_us') %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to (I18n.t 'menu.about_us'), root_path + "#about_us" %></li>
              <li class="divider"></li>
              <li><%= link_to (I18n.t 'menu.how_it_works'), root_path + "#how_it_works" %></li>
            </ul>
          </li>-->
          <li><%= link_to (I18n.t 'menu.about_us'), root_path + "#about_us" %></li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= (I18n.t 'menu.whom_is_our_service_for') %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to (I18n.t 'menu.for_stores'), root_path + "#delivery_for_stores" %></li>
              <li class="divider"></li>
              <li><%= link_to (I18n.t 'menu.for_delivery_companies'), root_path + "#for_delivery_companies" %></li>
              <!--<li class="divider"></li>
              <li><%= link_to (I18n.t 'menu.delivery_for_all'), root_path + "#delivery_for_all" %></li>-->
            </ul>
          </li>
          <li><%= link_to (I18n.t 'menu.blog'), blogs_path + "#blog" %></li>
          <li><%= link_to (I18n.t 'menu.contact_us'), root_path + "#contact_us" %></li>
          <!--<li><%= link_to "Home", root_path %></li>-->
          <!--<li><%= link_to "Help", root_path %></li>-->
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             <% if I18n.locale == :ru %>
                  <%= image_tag("ru.png", alt: "RU")+ (" RU") %>
              <% elsif I18n.locale == :ua %>
                  <%= image_tag("ua.png", alt: "UA")+ (" UA") %>
             <%else %>
                  <%= image_tag("eng.png", alt: "EN")+ (" EN") %>
             <% end %>
              <!--<%= (I18n.t 'menu.language') %> <b class="caret"></b>-->
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to image_tag("eng.png", alt: "EN")+ (" EN"), params.merge({:locale => :en}) %></li>
              <li><%= link_to image_tag("ru.png", alt: "RU")+ (" RU"), params.merge({:locale => :ru}) %></li>
              <li><%= link_to image_tag("ua.png", alt: "UA")+ (" UA"), params.merge({:locale => :ua}) %></li>
            </ul>
          </li>
          <li><%= link_to ("SaaS"), 'http://saas.teleport-ds.com', :target => "_blank" %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta content="<%= I18n.t 'content.tags'[0..244] %>" name="keywords" />
    <meta name="author" content="Alexandr Basan" />
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= favicon_link_tag 'teleport_16_16_0.png' %>
    <script type="text/javascript">
        $(document).ready(function(){
            $("#myCarousel").carousel({
                interval : 5000,
                pause: false
            });
        });
    </script>
    <!--Google Analytics-->

    <!--Google Analytics-->
    <!-- Google maps -->
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    <%= javascript_include_tag "google_maps" %>
    <!-- Google maps -->
    <%= javascript_include_tag "highcharts" %>
    <%= yield(:head) %>
  </head>
  <body onload="initialize(), setMarkers()">
    <%= render 'layouts/header' %>
    <%= content = yield %>
    <!--Back To Top Button-->
    <% if content.length > 1200 %>
      <%= link_to("#top") do %>
          <div id="backtotop" style="display: block;">
          </div>
      <% end %>
  <% end %>
  <!-- Words -->
  <% if request.url.include?('blog') %>
  <% else %>
      <p></p>
      <div class="container text-justify" style="color: #999999;" id="delivery_for_all_companies" name="delivery_for_all_companies">
        <%= t ('content.tags_view') %>
      </div>
  <% end %>
  <% if current_user.try(:admin?) %>
      <%= render 'layouts/admin' %>
  <% else %>
  <% end %>
      <div class="container">
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
      </div>

  <!-- Код тега ремаркетинга Google -->

  <!-- Код тега ремаркетинга Google -->
  </body>
</html>